### ISSUE TITLE
Implementing Screen II

### ISSUE THREAD

**Issue by AyyLMAO99** [Trikley/AwesomePlayer#15]
Bei Screen II haben wir nie darüber nachgedacht, dass wir eine Progressbar haben, die anzeigt, wie weit das Lied fortgeschritten ist.

**Comment by tooxoot** [comment]
![English Motherfucker! Do you speak it?](https://img.buzzfeed.com/buzzfeed-static/static/2013-10/enhanced/webdr06/30/15/original-grid-image-7813-1383160305-32.jpg?crop=275:182;0,0&downsize=715:*&output-format=auto&output-quality=auto)

**Comment by AyyLMAO99** [comment]
Songtitle bar is missing in our documentation of Screen II. 
Plz add @tooxoot

**Comment by tooxoot** [comment]
See #22
