### ISSUE TITLE
Implementing TopDownButton on all fragments

### ISSUE THREAD

**Issue by AyyLMAO99** [Trikley/AwesomePlayer#16]

**Comment by tooxoot** [comment]
![English Motherfucker! Do you speak it?](https://img.buzzfeed.com/buzzfeed-static/static/2013-10/enhanced/webdr06/30/15/original-grid-image-7813-1383160305-32.jpg?crop=275:182;0,0&downsize=715:*&output-format=auto&output-quality=auto)
