### ISSUE TITLE
Create something resembling architecture

### ISSUE THREAD

**Issue by Trikley** [Trikley/AwesomePlayer#28]
Before we continue developing the PlayerFragment and the PlayerService we should agree on one architectural solution for our project. 

That was the convoluted way of saying: We need some datastructure to back this shit up. We can´t just work with querys on the MediaStore, we will need to save the results of those querys in objects created for that purpose. For example a song object, which could then be passed on to different Components of this mess.

**Comment by tooxoot** [comment]
OK. What do you need for the playback?
The `simpleCursorAdapter` from the underlying `CursorListFragment` is able to provide a simple List of item-ids.  
The exact content of the results can only be obtained by overriding the `onLoadFinished` method for each of the ListFragments. By doing so it would be possible to obtain the needed information by iterating over the `Cursor data` parameter.

**Comment by tooxoot** [comment]
Discussed on 28.06.2017
